
import React, { useState, useEffect, useRef } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { analyzeAnswers } from '../../services/geminiService';
import { Answer, ReportData } from '../../types';
import { useAuth } from '../../hooks/useAuth';
import Spinner from '../ui/Spinner';
import Button from '../ui/Button';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { Download, BrainCircuit, Lightbulb, ShieldCheck, Heart, AlertTriangle } from 'lucide-react';

const Report: React.FC = () => {
  const [report, setReport] = useState<ReportData | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [isDownloading, setIsDownloading] = useState(false);
  const [error, setError] = useState('');
  const location = useLocation();
  const navigate = useNavigate();
  const { user } = useAuth();
  const reportContentRef = useRef<HTMLDivElement>(null);
  
  const answers: Answer[] | undefined = location.state?.answers;

  useEffect(() => {
    const loadReport = async () => {
      if (!user) {
        navigate('/login');
        return;
      }
      
      const reportKey = `mindwell-report-${user.id}`;

      try {
        setError('');
        setIsLoading(true);

        if (answers && answers.length > 0) {
          // Generate a new report
          const analysis = await analyzeAnswers(answers);
          setReport(analysis);
          localStorage.setItem(reportKey, JSON.stringify(analysis));
        } else {
          // Try to load a saved report
          const savedReport = localStorage.getItem(reportKey);
          if (savedReport) {
            setReport(JSON.parse(savedReport));
          } else {
            // No answers and no saved report, go back
            navigate('/dashboard');
            return;
          }
        }
      } catch (e) {
        setError((e as Error).message);
      } finally {
        setIsLoading(false);
      }
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
    loadReport();
  }, [answers, navigate, user]);

  const handleDownloadPdf = async () => {
    const reportElement = reportContentRef.current;
    if (!reportElement) return;
    setIsDownloading(true);
    try {
        const canvas = await html2canvas(reportElement, {
            scale: 2, 
            useCORS: true,
            onclone: (document) => { // Force white background for PDF
              const clonedElement = document.getElementById('pdf-content');
              if(clonedElement) {
                clonedElement.style.backgroundColor = 'white';
                clonedElement.classList.remove('dark:bg-slate-800');
              }
            }
        });
        const imgData = canvas.toDataURL('image/png');
        const pdf = new jsPDF('p', 'mm', 'a4');
        const pdfWidth = pdf.internal.pageSize.getWidth();
        const imgWidth = canvas.width;
        const imgHeight = canvas.height;
        const ratio = imgWidth / imgHeight;
        const imgPdfHeight = (pdfWidth / ratio);
        
        pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, imgPdfHeight);
        pdf.save('MindWell_AI_Report.pdf');
    } catch(e) {
        console.error("Error generating PDF", e);
        setError("Sorry, there was an issue creating your PDF.");
    } finally {
        setIsDownloading(false);
    }
  };

  if (isLoading) {
    return (
      <div className="flex flex-col items-center justify-center h-64">
        <Spinner size="lg" />
        <p className="mt-4 text-slate-500 flex items-center gap-2"><BrainCircuit size={20}/> Analyzing your responses...</p>
      </div>
    );
  }

  if (error) {
    return <div className="text-center text-red-500 bg-red-100 dark:bg-red-900/20 p-4 rounded-lg">{error}</div>;
  }
  
  if (!report) {
    return null; // or some other placeholder
  }
  
  const renderListItem = (text: string) => (
    <li key={text} className="flex items-start gap-3">
        <div className="w-1.5 h-1.5 bg-teal-500 rounded-full mt-2.5 flex-shrink-0"></div>
        <span>{text}</span>
    </li>
  );

  return (
    <div className="max-w-4xl mx-auto animate-fade-in">
        <div id="pdf-content" ref={reportContentRef} className="p-6 sm:p-10 bg-white dark:bg-slate-800 shadow-xl rounded-lg">
            <header className="border-b-2 border-slate-200 dark:border-slate-700 pb-4 mb-6">
                <h1 className="text-3xl font-bold text-slate-800 dark:text-white">Personal Wellness Report</h1>
                <p className="text-slate-500 dark:text-slate-400">Generated by MindWell AI</p>
            </header>
            
            <section className="mb-6">
                <h2 className="text-xl font-semibold flex items-center gap-2 text-teal-600 dark:text-teal-400 mb-3"><Heart size={22} /> Overall Summary</h2>
                <p className="text-slate-600 dark:text-slate-300 leading-relaxed">{report.summary}</p>
            </section>

            <div className="grid md:grid-cols-2 gap-6 mb-6">
                <section>
                    <h2 className="text-xl font-semibold flex items-center gap-2 text-amber-600 dark:text-amber-400 mb-3"><AlertTriangle size={22} /> Potential Areas of Concern</h2>
                    <ul className="space-y-2 text-slate-600 dark:text-slate-300">{report.concerns.map(renderListItem)}</ul>
                </section>
                <section>
                    <h2 className="text-xl font-semibold flex items-center gap-2 text-green-600 dark:text-green-400 mb-3"><ShieldCheck size={22} /> Potential Strengths</h2>
                    <ul className="space-y-2 text-slate-600 dark:text-slate-300">{report.strengths.map(renderListItem)}</ul>
                </section>
            </div>
            
            <section className="mb-6">
                <h2 className="text-xl font-semibold flex items-center gap-2 text-blue-600 dark:text-blue-400 mb-3"><Lightbulb size={22} /> Actionable Suggestions</h2>
                <ul className="space-y-2 text-slate-600 dark:text-slate-300">{report.suggestions.map(renderListItem)}</ul>
            </section>

            <footer className="mt-8 pt-4 border-t-2 border-slate-200 dark:border-slate-700">
                <h3 className="font-bold text-red-600 dark:text-red-400">Important Disclaimer</h3>
                <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">{report.disclaimer}</p>
            </footer>
        </div>
        <div className="mt-8 text-center">
            <Button onClick={handleDownloadPdf} isLoading={isDownloading}>
                <Download size={20} className="mr-2" />
                Download Report as PDF
            </Button>
        </div>
    </div>
  );
};

export default Report;
